### ISSUE TITLE
how to manually set clean?

### ISSUE THREAD

**Issue by simon1tan** [rubentd/dirrty#14]
I looked at the source and there is a setClean function but I can't figure out how to call it.  I tried to $('form').trigger('clean') and $('form').trigger('setClean') but they don't seem to do anything.

**Comment by simon1tan** [comment]
Nevermind. Didn't need to do this at all. Would still be nice to know how to do it though.

**Comment by invious** [comment]
how do you manually set clean/dirty?

**Comment by lenamtl** [comment]
These function are available from this fork
https://github.com/simontaite/jquery.dirty

**Comment by inquisitive-stha** [comment]
@simon1tan did you find it? 
@lenamtl is this the fork of this jquery.dirrty? It does not work, in fact, it does not prevent loading on any scenario.

**Comment by lenamtl** [comment]
Hi,

What I did a few years ago is I have implement some of the features of the fork of Simon into the Ruben code because I was already customized it and have not the time to test Simon fork at that 
time see my old post https://github.com/simontaite/jquery.dirty/issues/1

So I'm using a fork of two script, as my code is old it won't bring anything that Simon fork have...

What you can do if you just start using it is to try the Simon fork to see if it work as expected.
Simon is active and he is willing to add new features when he have time :)
